### ISSUE TITLE
Need help with the error thrown by snowtransfer: [ERROR] Error when sending Discord DM: TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by KumiFluff** [DasWolke/SnowTransfer#41]
I was using snowtransfer for sending the messages to the users from my bot. It works well for the most part but while sending the dm to one of the users I got this error: [ERROR] Error when sending Discord DM: TypeError: Cannot read properties of undefined (reading 'id') This error broke the application while in production. I would like it so that this issue doesn't happen in future and doesn't break my bot. Has anyone here encountered this issue before? Since I am kinda unable to reproduce it at the moment.

Here's the code snippet from where I send the dm

```
export async function sendDiscordDM(userId: string, message: string) {
  const client = new SnowTransfer(process.env.DISCORD_BOT_TOKEN);
  try {
    const dm = await client.user.createDirectMessageChannel(userId);
    await client.channel.createMessage(dm.id, { content: message });
  } catch (err) {
    console.error(`Error when sending Discord DM: ${err}`);
  }
}

```
As suggested in the code above, it breaks at dm.id which means that dm is undefined. For some reason I am unable to reproduce this. I would like to know the reason behind why it would have happened so that it doesn't break on my prod bot again. Any help regarding this would be appreciated.

**Comment by PapiOphidian** [comment]
Hi! Thanks for your report.

I've reviewed the flow of the code in SnowTransfer to see if it's possible this is something I messed up or can fix and nothing in particular stood out to me. SnowTransfer for the most part just returns whatever the API returns and if the API returned a 204 no content, then that's when undefined would have been returned from SnowTransfer.

Since you cannot reproduce the error and I personally have never run into this issue, I'm gonna blame Discord's API on this one. If you manage to run into the error again, do tell and we'll see what we can do! Next time, include the full error including the stack trace so I know who to blame more easily and include which SnowTransfer version you're using.

SnowTransfer is minified, but does include source maps which you can load to get the error stacks to point to the TypeScript files I work with.
